name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
          - name: Caching Dependencies
            uses: actions/cache@v4  # Caches dependencies for faster builds
            with:
              path: |
                ~/.cargo/registry
                ~/.cargo/git
                target
              key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
              restore-keys: |
                ${{ runner.os }}-cargo-
          - uses: actions/checkout@v4
          - name: Build
            run: cargo build --verbose
          - name: Run tests
            run: cargo test --verbose
     
          - name: Login to Container Registry 
            uses: docker/login-action@v3
            with:  
              registry: ghcr.io 
              username: ${{ github.actor }}  
              password: ${{ secrets.TOKEN }}  

          - name: Build and push Docker image
            uses: docker/build-push-action@v6
            with:
              context: .
              push: true
              tags: | 
                ghcr.io/${{ secrets.REPOSITORY }}/${{github.REPOSITORY}}sha-${{ github.sha }}
                ghcr.io/${{ secrets.REPOSITORY }}/${{github.REPOSITORY}}:branch-${{ github.ref_name }}
                ghcr.io/${{ secrets.REPOSITORY }}/${{github.REPOSITORY}}:latest
              platforms: linux/amd64,linux/arm64 
